### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by miguelpduarte** [NIAEFEUP/nijobs-fe#11]
Add Error Handling component to simplify displaying errors from either requests or from the application itself

**Comment by imnotteixeira** [comment]
The errors will be dealt on a case by case level, and not globally, therefore this is not actually an issue.

When developing a part of the application, you can either have an [Error Boundary](https://reactjs.org/docs/error-boundaries.html) to deal with the error in last resort or implement a way to handle the errors more specifically
