### ISSUE TITLE
Change createMuiTheme usages to createTheme

### ISSUE THREAD

**Issue by TiagooGomess** [NIAEFEUP/nijobs-fe#119]
The Material-UI createMuiTheme function was renamed to createTheme. More information is available [here](https://next.material-ui.com/guides/migration-v4/#theme).

![Screenshot from 2021-08-08 20-05-07](https://user-images.githubusercontent.com/50210213/128643034-46d38970-ec08-4306-93cc-f12875b17b65.png)

The usages of that function should be renamed accordingly.

**Comment by DoStini** [comment]
I'm not having this problem in develop, is it in another branch?

**Comment by TiagooGomess** [comment]
> I'm not having this problem in develop, is it in another branch?

The problem is in the `feature/view-offer-page` branch and started after fixing the audit issues. Maybe we can fix this only after merging it to the `develop`.

**Comment by DoStini** [comment]
Seems good, I'll wait

**Comment by DoStini** [comment]
@TiagooGomess Is this still a problem?

**Comment by TiagooGomess** [comment]
> @TiagooGomess Is this still a problem?

Yes, it can be fixed now.
