### ISSUE TITLE
Create a Mobile View for the Tables

### ISSUE THREAD

**Issue by monkin77** [NIAEFEUP/nijobs-fe#132]
Right now, the tables are not implemented for Mobile, both in the My Offers Page and in Company Reviews.

**Comment by TiagooGomess** [comment]
Design suggestion: https://www.pinterest.com/pin/5770305763381702/

**Comment by TiagooGomess** [comment]
In mobile view, display just the company's name and the state. You can use 3 icons to distinguish the 3 states: approved, rejected, or pending.

**Comment by monkin77** [comment]
- [ ] Add actions to mobile tables
- [ ] Also adapt CompanyOffersPage
