### ISSUE TITLE
Unclear unexpected error in enable offer button in view page as a company

### ISSUE THREAD

**Issue by DoStini** [NIAEFEUP/nijobs-fe#139]
When trying to enable an offer that causes max concurrent offers error, it throws an unexpected error.
It should be clear why the offer was not able to be enabled. This problem will also probably occur when an offer was blocked by an admin

**Comment by TiagooGomess** [comment]
Add an entry [here](https://github.com/NIAEFEUP/nijobs-fe/blob/develop/src/utils/offer/OfferUtils.js), with the key `max-concurrent-offers`.
