### ISSUE TITLE
Use google maps api to select job location

### ISSUE THREAD

**Issue by DoStini** [NIAEFEUP/nijobs-fe#143]

**Comment by imnotteixeira** [comment]
Commenting here for visibility:

This was the first API I looked into when starting the development on the widget. It has a free tier (but we would still have to link a credit card, so there's always the risk of a huge bill regardless)

And honestly, it does not bring that much value (we only need city granularity, no need for the exact place on the map), and cities do not change that much, so we would be pretty safe with a static db of our own with a list of cities-countries (possibly with lat+long coords to show a map in the city center or something, but that's it)
