### ISSUE TITLE
Use custom service for location picker

### ISSUE THREAD

**Issue by DoStini** [NIAEFEUP/nijobs-fe#152]
Currently, we are using [Geodb Cities API](https://rapidapi.com/wirefreethought/api/geodb-cities/), which is very incomplete. For example, Aveiro is not available.

We should implement our own service to use in the create offer page location picker. We have an available json file containing every city

**Comment by DoStini** [comment]
@imnotteixeira Should we do this as an npm package or do you think it could be integrated under our own API

**Comment by imnotteixeira** [comment]
Good practices dictate we should separate it, but I don't mind having it coupled as it won't change much, and it would only make sense to separate if there were more dependencies for it. And if there were, it would mean it would have to be maintained, support different use cases.

Let's keep it simple and within our API for now.

**Comment by DoStini** [comment]
I have created https://github.com/NIAEFEUP/nijobs-be/issues/199 for further discussion

**Comment by Naapperas** [comment]
This is related to #235
