### ISSUE TITLE
Add Create Offer option to admin and company UserMenu

### ISSUE THREAD

**Issue by TiagooGomess** [NIAEFEUP/nijobs-fe#154]
Add an option to the UserMenu, similar to the CompanyApplications that redirects the user to the create offer page. This option should be available to the companies and the admins.

![image](https://user-images.githubusercontent.com/50210213/148654833-6923c2c4-afb0-42df-bf00-279313a1bd62.png)

You can add the necessary code in [this](https://github.com/NIAEFEUP/nijobs-fe/blob/develop/src/components/Navbar/UserMenu.js#L130) file.

**Comment by toni-santos** [comment]
I saw there were 2 functions related to the Menu Options, one for companies ([CompanyMenuOptions](https://github.com/NIAEFEUP/nijobs-fe/blob/9135244b9e3a93cd0a675f85ae85b03046668798/src/components/Navbar/UserMenu.js#L89)) and one for admins ([AdminMenuOptions](https://github.com/NIAEFEUP/nijobs-fe/blob/9135244b9e3a93cd0a675f85ae85b03046668798/src/components/Navbar/UserMenu.js#L56)), should I add the new button on each of these menus or keep it in a generalized section such as [UserMenuContent](https://github.com/NIAEFEUP/nijobs-fe/blob/9135244b9e3a93cd0a675f85ae85b03046668798/src/components/Navbar/UserMenu.js#L130)?

**Comment by TiagooGomess** [comment]
@toni-santos You should add the button in the two functions because it's a feature that both the companies and the admins have. That way, in the future, we can have a new role that cannot create offers (for example, a student role).
