### ISSUE TITLE
Add simple FE tests

### ISSUE THREAD

**Issue by miguelpduarte** [NIAEFEUP/nijobs-fe#18]
See https://github.com/NIAEFEUP/nijobs-fe/pull/13#discussion_r310816086

Use something like `jest`'s snapshot tests initally, possibly including some simple cases of [`react-testing-library`](https://github.com/testing-library/react-testing-library).

Add code coverage and configure CI to run it, possibly allowing the addition of it to branch protection :smile:

**Comment by imnotteixeira** [comment]
Closed via #13
