### ISSUE TITLE
Make Show Filters Button always visible

### ISSUE THREAD

**Issue by TiagooGomess** [NIAEFEUP/nijobs-fe#186]
When there are many offers, we need to scroll, and as a consequence, the `Show Filters` button is not visible. If the user wants to see the filters, he needs to scroll up, which can take a lot of time (for example, if he had scrolled 100 offers).

|   |   |
|---|---|
| ![1](https://user-images.githubusercontent.com/50210213/155188366-ccdaa1b0-f33a-4921-a8f4-c5e3d8aced4d.png) |  ![image](https://user-images.githubusercontent.com/50210213/155188334-bef91abd-208f-448d-a324-620b0ade1036.png) |

**Comment by DoStini** [comment]
Also, as a suggestion given by Marta from the commercial team, the button itself could be something like "Adjust search" or "Adjust filters" instead of "show"

**Comment by pedrosilva17** [comment]
I've run into a problem: The button now behaves as intended (staying on top of the offers container while scrolling) and its title was changed, but I cannot click on it whenever the button is on top of any offer, as if the offers have priority over the filter button. I'm searching online for a fix but so far I haven't found anything.

**Comment by TiagooGomess** [comment]
> I've run into a problem: The button now behaves as intended (staying on top of the offers container while scrolling) and its title was changed, but I cannot click on it whenever the button is on top of any offer, as if the offers have priority over the filter button. I'm searching online for a fix but so far I haven't found anything.

@pedrosilva17 Please open a draft pull request with the code you have so that we can help you.
