### ISSUE TITLE
Change job duration slider and offer indication to 12+ instead of 12

### ISSUE THREAD

**Issue by DoStini** [NIAEFEUP/nijobs-fe#190]

**Comment by DoStini** [comment]
My current idea would be that the last value of the slider was the 12+. I think this is important for the MVP (as of now it could be just as I described) as companies usually have full time offers that go beyond 12 months, don't you think?

**Comment by limwa** [comment]
This has already been taken care of in #159, I think.

[This line](https://github.com/NIAEFEUP/nijobs-fe/blob/develop/src/components/Offers/New/form-components/JobDurationComponent.js#L23) is what implements that change.
