### ISSUE TITLE
Write rules

### ISSUE THREAD

**Issue by DoStini** [NIAEFEUP/nijobs-fe#196]

**Comment by Naapperas** [comment]
Maybe I could change `rules.json` to be a JS file, that way we could import the `max_concurrent_offers` value (from `nijobs-commons`, possibly) and use it when referencing the amount of concurrent offers one company can have at a time. What do you think @DoStini @imnotteixeira ?

**Comment by imnotteixeira** [comment]
> Maybe I could change `rules.json` to be a JS file, that way we could import the `max_concurrent_offers` value (from `nijobs-commons`, possibly) and use it when referencing the amount of concurrent offers one company can have at a time. What do you think @DoStini @imnotteixeira ?

Makes sense
