### ISSUE TITLE
Reduce amount of PR checks

### ISSUE THREAD

**Issue by miguelpduarte** [NIAEFEUP/nijobs-fe#23]
The number of checks in a PR is too damn high! This creates a lot of noise, which is less than ideal.

I'd suggest keeping it down to 3 or so, as I believe that most of Netlify's stuff can be disabled without much loss.

**Comment by miguelpduarte** [comment]
Assigning @imnotteixeira as I believe he was responsible for this setup 😜

**Comment by imnotteixeira** [comment]
After doing some research, looking into the netlify settings and checking out the documentation regarding the `netlify.toml` file, I'm afraid the netlify checks are not customizable

**Comment by imnotteixeira** [comment]
Update: It turns out this customization was well hidden in the netlify settings page (thanks Netlify UX guys), and it should be resolved.
