### ISSUE TITLE
Configurar Linting e Git hooks

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-fe#3]
Correr o lint no pre commit

**Comment by DuarteOliveira8** [comment]
Para o lint escolhi usar ESLint e estive à procura de algumas opções de lint específicas para React. Encontrei o [eslint-plugin-react](https://www.npmjs.com/package/eslint-plugin-react) que é recomendado pelo [ESLint](https://www.npmjs.com/package/eslint#does-eslint-support-jsx).

Entre as várias opções escolhi algumas que achei necessárias e úteis para manter o nosso código organizado e evitar erros o máximo possível. Isto também vai ajudar pessoal que está a começar a aprender ReactJS, pois evita muitos erros de transição de HTML para JSX.

As opções escolhidas do ESLint foram as seguintes:
- As opções [recomendadas](https://eslint.org/docs/rules/) pelo ESLint para evitar erros comuns de JavaScript.
- [indent](https://eslint.org/docs/rules/indent): Manter indentação consitente (opção: 4 espaços).
- [brace-style](https://eslint.org/docs/rules/brace-style): Consistência no brace style (opção: "1tbs").
- [camelcase](https://eslint.org/docs/rules/camelcase): Usar camel case em todas as variáveis e funções.

As opções escolhidas especificamente para React foram as seguintes:

- [react/jsx-no-comment-textnodes](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-no-comment-textnodes.md): Não fazer commentários de JavaScript em JSX.
- [react/jsx-no-duplicate-props](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-no-duplicate-props.md): Evitar props duplicadas nos componentes de JSX.
- [react/jsx-no-target-blank](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-no-target-blank.md): Não usar `target='_blank'` sem `rel='noreferrer noopener'` pois pode levar a vulnerabilidades.
- [react/jsx-no-undef](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-no-undef.md): Evitar componentes JSX não definidos (com a opção "allowGlobals" para considerar o global scope).
- [react/jsx-uses-react](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-uses-react.md): Evitar includes de React quando não é necessário.
- [react/jsx-uses-vars](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-uses-vars.md): Evitar componentes de JSX não usados.
- [react/no-children-prop](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/no-children-prop.md): Não passar children pelas props.
- [react/no-deprecated](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/no-deprecated.md): Evitar a utilização de métodos que já não são suportados pelo React.
- [react/no-direct-mutation-state](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/no-direct-mutation-state.md): Apenas modificar o state no construtor ou com setter.
- [react/no-unescaped-entities](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/no-unescaped-entities.md): Evitar caracteres mal posicionados.
- [react/no-unknown-property](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/no-unknown-property.md): Evitar usar propriedes da DOM não existentes. **Fixable**
- [react/require-render-return](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/require-render-return.md): Obrigar o return na função de render dos componentes.
- [react/prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/prop-types.md): Declarar sempre prop-types para melhorar a reutilização de componentes.
- [react/no-unused-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/no-unused-prop-types.md): Evitar declaração de prop-types não usados.
- [react/no-unused-state](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/no-unused-state.md): Evitar declaração de estados não usados.
- [react/self-closing-comp](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/self-closing-comp.md): Evitar closing tags a mais em componentes sem children. **Fixable**
- [react/void-dom-elements-no-children](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/void-dom-elements-no-children.md): Não colocar children em componentes self-closing.
- [react/jsx-closing-tag-location](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-closing-tag-location.md): Reforçar identação dos closing tags. **Fixable**
- [react/jsx-closing-bracket-location](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-closing-bracket-location.md): Reforçar a localização do fecho do tag para o caso de elementos que ocupam multiplas linhas. **Fixable**
- [react/jsx-equals-spacing](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-equals-spacing.md): Evitar espaços antes e depois do `=` nos elementos de JSX (opção "never"). **Fixable**
- [react/jsx-indent](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-indent.md): Reforçar a indentação em JSX (4 espaços). **Fixable**
- [react/jsx-indent-props](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-indent-props.md): Reforçar a indentação das props (4 espaços). **Fixable**
- [react/jsx-max-props-per-line](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-max-props-per-line.md): Limitar numero de props por linhas (opções: 1 prop, multiline). **Fixable**
- [react/jsx-one-expression-per-line](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-one-expression-per-line.md): Obrigar a utilização de um tag por linha (opção: "none"). **Fixable**
- [react/jsx-pascal-case](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-pascal-case.md): Reforçar a utilização de PascalCase para componentes.

**Comment by imnotteixeira** [comment]
Até agora, parecem-me bem as rules

Para correr o lint no pre-commit recomendo o `husky` (https://github.com/typicode/husky), é o que estamos a usar na API-SIGARRA e é muito fácil de configurar

**Comment by DuarteOliveira8** [comment]
Sim, o António já esteve a ver essa opção! Vamos usar o husky então.

**Comment by imnotteixeira** [comment]
This might help

https://www.npmjs.com/package/eslint-plugin-more-naming-conventions?activeTab=readme

**Comment by DuarteOliveira8** [comment]
Pelo que percebi dos exemplos, @imnotteixeira, esse plugin faz com que as funções fiquem em PascalCase e não em camelCase. Mas para variáveis em snake_case é uma boa opção!

Também me apercebi que a opção de camelcase do eslint é só para variáveis. Vou ter de ver melhor opções para naming.

Quanto a classes ficarem em PascalCase, já adicionei isso para os componentes de ReactJS. Acho que não haverá mais classes para além dos componentes, por isso não acho que seja preciso uma opção adicional no eslint, mas posso estar errado.

**Comment by imnotteixeira** [comment]
pelo que vi do eslint, o camelcase é para vars e funções, o que seria um problema porque ativando os 2 pode dar conflito, mas nada como testar. Seria camelcase para aplicar a vars e funçoes camelcase, e depois o outro do snake case so para vars

**Comment by miguelpduarte** [comment]
@DuarteOliveira8 Acho que poderiam haver outras "classes" que não seriam components, usadas possivelmente para data processing ou assim. Mas entretanto já pensei nisso e falei também com o @imnotteixeira e ambos concordamos que isso seriam ficheiros de utils standalone que exportariam funções diretamente então seria tranquilo (mesma ideia que ter classes com funções static, mas assim facilitaria importar e afins, imo - se são funcionalmente equivalentes não há razão para complicar com uma classe)

**Comment by imnotteixeira** [comment]
Done in #6
