### ISSUE TITLE
Fix text-cropping when email is too big

### ISSUE THREAD

**Issue by Naapperas** [NIAEFEUP/nijobs-fe#322]
As in this screenshot:
![image](https://github.com/NIAEFEUP/nijobs-fe/assets/23704084/fc1d1636-1d75-43c0-b55e-359bc2afc104)
If a user's email is too long, some text might be cropped, this should be taken care of.

**Comment by imnotteixeira** [comment]
Even worse than that is the cropped "c" in "company applications", please fix that as well
