### ISSUE TITLE
Fix "Why do I need to apply?" text

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-fe#59]
This is the message shown when the user clicks on the "Why do I need to apply?" link on the Company Application page.

![image](https://user-images.githubusercontent.com/28157246/101984057-ba0aa780-3c76-11eb-8a9a-8b3db0ed2488.png)

We should rephrase the last two paragraphs as follows:

"As this platform is made by students, for students, we oversee the entries so that we can make sure that both our and the participating companies' expectations are satisfied.

Once you're accepted, you will receive an email from us, and you will be able to customize your profile further (Add a nice Bio, and a Company Logo, as well as your contacts)"

**Comment by Saviour1001** [comment]
Did the requested changes and generated the pull request

**Comment by 96RadhikaJadhav** [comment]
@imnotteixeira  Could you please assign this issue to me? I wish to work on it.

**Comment by imnotteixeira** [comment]
@96RadhikaJadhav As you can clearly see, there was already a PR open for this (#60) as stated by the comment above

@both this repo is for internal consumption. Exceptionally, we will merge #60 as this has no complexity and is just a text change, otherwise, we like to keep it to our internal maintainers

**Comment by 96RadhikaJadhav** [comment]
> @96RadhikaJadhav As you can clearly see, there was already a PR open for this (#60) as stated by the comment above
> 
> @both this repo is for internal consumption. Exceptionally, we will merge #60 as this has no complexity and is just a text change, otherwise, we like to keep it to our internal maintainers

@imnotteixeira As the PR was not merged yet, I thought I can give it a try. Anyway no issues. Thank you :)
