### ISSUE TITLE
Create a `Rules` page

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-fe#63]
We need to have a page where we specify the usage rules, such as the max duration of the offer publishing, max number of concurrent offers for a company, etc...

Just from the top of my head, we want to show them in three places, at least (home page - with a link that goes to specific page, and when completing the registration - with a modal, so as not to disrupt the experience by moving to a different page, we can also have this modal on the offer creation page)

In order to support these multiple cases, we don't hant to replicate the rule definitions everywhere, so we should have a file that exports an array of rules (strings), and the components that show them, simply use that array and format them at will, so the content will always be the same.

Before doing this, we should define the rules clearly, if you pick this issue, we should define the rules in a comment of this issue later on!

**Comment by miguelpduarte** [comment]
This could either be a component with HTML to support markup, or maybe even a Markdown file? Given that [remarkable ](https://github.com/jonschlinkert/remarkable) is not in this project yet, we could either add it if we see that it would be useful (for job descriptions for example) or use a hardcoded component.

This strings option you mentioned also seems like a good simple option but might be a bit too limited if we want something that is more customizable.

**Comment by imnotteixeira** [comment]
That would actually be the opposite of customizable. The idea of having strings only is that we can present them in different ways, depending on the scenario. We could have a modal with a list, another page with rules where each has an icon, another where you have them "paginated" in a sort of introduction/tutorial thing. Having the html/md already locked would make it harder.
