### ISSUE TITLE
Register and Login pages

### ISSUE THREAD

**Issue by miguelpduarte** [NIAEFEUP/nijobs-fe#7]
Pages to add:
* Register
* Login
* Apply for our site

The login page should have the following inputs:
* Email
* Password

The register page should have the following inputs (should be able to receive the one-time token from the URL - not yet in use):
* Email
* Nome da empresa
* Password

The apply for our site page should have the following inputs:
* Email
* Nome da empresa
* Motivação
* Outros contactos

**Comment by imnotteixeira** [comment]
After further discussion, this is no longer the required work. Here is the updated version of this issue:

Pages to add:

- Complete registration (the approved users already have an account, so they will need to provide a company logo and bio on first login - they can also update their password if desired )
- Login

The login page should have the following inputs:
* Email
* Password

The register part should be a progress-like step-by-step process of completing the missing information. Steppers are a nice touch (https://material-ui.com/components/steppers/)

**Comment by imnotteixeira** [comment]
Also, as discussed offline with @miguelpduarte, we will implement the login state details using SWR (https://swr.now.sh/), as it can be a much-requested piece of information by various parts of the application, thus using a cache-ready approach seems reasonable.
