### ISSUE TITLE
Create and view Post Page

### ISSUE THREAD

**Issue by miguelpduarte** [NIAEFEUP/nijobs-fe#8]
Information to request and to show:
* Tags
* Localização
* Tipo de emprego
* Título
* Descrição
* Data de início e duração (podem ser indefinidas)
* Vagas
* Checkbox de ser remunerado ou não (mostrar no site mas não ter como critério de filtragem)
* Requisitos (formato form do Postman)

**Comment by imnotteixeira** [comment]
Splitting this into multiple issues for better tracking and discussion. Check #84, #85 and #86.

Closing due to redundancy.
