### ISSUE TITLE
View Offer page

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-fe#85]
Currently, can be viewed through the Search Results Widget. The code should be refactored and generalized in a way the the `<OfferContent>` can be used both in the widget and in a View Offer page, so that offers can be shared through links.

This page should follow the application layout, and be mobile-friendly. It should just be a page wrapper on the current `<OfferContent/>`

It should be served at `offer/:offerId`

**Comment by imnotteixeira** [comment]
Whoever takes this should look at the Offer model in [NIAEFEUP/nijobs-be](https://github.com/NIAEFEUP/nijobs-be) and update the `OfferContent` component to have all the necessary info

**Comment by TiagooGomess** [comment]
@imnotteixeira When we click on an offer in the search results, should we be redirected to that offer page, or that is supposed to be as it is, and the page is only accessible through the link?

**Comment by imnotteixeira** [comment]
The current behavior should be kept. however, the offer title (in the OfferContent on the right, not the OfferIitem on the left) should turn into a link that takes the user to the page of the offer. Keep in mind that when reusing the component, the title should not be a link when you're in the offer page already
