### ISSUE TITLE
Edit Offer page

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-fe#86]
A page for companies to edit their offers.

It should be served at `/offer/:offerId/edit`

The layout should be the same as the create offer page (as much as possible), but with the fields already filled in with the current offer information.

**Comment by imnotteixeira** [comment]
State update after #113 @DoStini?

**Comment by DoStini** [comment]
Im starting to take a look into this issue. 

First I think I should do something similar as in View offer: 

https://github.com/NIAEFEUP/nijobs-fe/blob/9135244b9e3a93cd0a675f85ae85b03046668798/src/pages/OfferPage.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L18-L20

The thing is,  I need an EditPage controller but I also need to set the values in the common OfferFormController to control the actual form. To make this happen does the form controller need to be in the Route like I did in create offer page

**Comment by DoStini** [comment]
Can I inject this [Here](https://github.com/NIAEFEUP/nijobs-fe/blob/9135244b9e3a93cd0a675f85ae85b03046668798/src/components/Offers/New/CreateOfferForm.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L179-L199) and create the context both in CreateOfferPage and EditOfferPage (the upper layer of the offer form) and instantiate there the context?

**Comment by imnotteixeira** [comment]
I would extract the common logic of "putting" an offer to a different hook, to be used by the offerCreate controller and the edit one. They would need to specify the service function to use (create or edit api), and the edit would need to pass the default values (current offer values) as an argument of that hook.

This might sound complex, but really is just extracting common logic to another function (react hook)
