### ISSUE TITLE
Page re-mount on layout switching (mobile/desktop)

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-fe#87]
Currently, the way the PageLayout is set up, it renders the children wrapped in a `<div>` if !mobile, and wraps it in a `<Dialog>` otherwise.

Due to the reconciliation phase optimizations, every time a subtree root node changes type (in this case from `div` to `Dialog`), React will re-mount (not a simple re-render) everything from there.  https://reactjs.org/docs/reconciliation.html#elements-of-different-types

By doing so, every component loses its internal state, and re-renders with the initial state. I.e., if you are filling a form in desktop and change to mobile or vice-versa, the fields will be emptied out.

For things that are stored in Redux, this is not a problem, since the Redux Provider is above PageLayout, and so it will not reset, and the re-mounted components will just re-read the state from the Redux store and keep their changes on layout swap.

While I noticed this and think it shouldn't happen, is it really worth doing something about it? (When will a generic user switch from desktop to mobile or vice-versa, on the same session?)

---

If it is to be fixed, here are some solutions:

- Every state in Redux (bad) - It would require a lot of refactoring, and would crowd too much the Redux store with unnecessary data
- Have a Context provider for each specific PageLayout (better)
    - The PageLayout would provide a Context (https://reactjs.org/docs/context.html) for its children, so that they could read/store values there. They would use those as state. So, when changing between mobile and desktop subtrees, the state is still present in that page's context and can be restored.

Please share your view in the comments.

**Comment by miguelpduarte** [comment]
I'm inclined to label this as `wontfix` since how frequent will devices switch from one to the other?
